version: '3.9'
services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    ports:
      - 5555:5432
    environment:
      - "POSTGRES_USER=kong"
      - "POSTGRES_PASSWORD=pwdkong"
      - "POSTGRES_DB=kong"
  kong:
    image: kong:latest
    container_name: kong
    ports:
      - 9000:8000
      - 9443:8443
      - 9001:8001
      - 9444:8444
    networks:
      - kong-network
    environment:
      - "KONG_LOG_LEVEL=debug"
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=kong-database"
      - "KONG_PG_USER=kong"
      - "KONG_PG_PASSWORD=kong"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"

  networks:
    kong-network:
      driver: bridge
